#!/bin/bash
# ProjectHub - Complete Deployment Setup
# This script helps you deploy ProjectHub to GitHub and Railway

echo "================================"
echo "🚀 ProjectHub Deployment Setup"
echo "================================"
echo ""

# Step 1: GitHub Setup
echo "📝 STEP 1: Create GitHub Repository"
echo "================================"
echo ""
echo "Go to https://github.com/new and create a new repository:"
echo "  Repository name: project-manager"
echo "  Description: Full-stack project management application"
echo "  Public: Yes"
echo ""
echo "DO NOT initialize with README, .gitignore, or license"
echo ""
echo "After creating, copy the repository URL (HTTPS)"
echo ""
echo "Then run these commands:"
echo ""
echo "git remote add origin <your-repo-url-here>"
echo "git branch -M main"
echo "git push -u origin main"
echo ""

# Step 2: Railway Setup
echo ""
echo "⚙️ STEP 2: Deploy to Railway"
echo "================================"
echo ""
echo "1. Go to https://railway.app"
echo "2. Sign up/Login with GitHub"
echo "3. Create new project → Deploy from GitHub"
echo "4. Select your project-manager repository"
echo "5. Railway will auto-detect services"
echo ""
echo "6. Add PostgreSQL plugin (generates DATABASE_URL)"
echo ""
echo "7. Configure Backend Service:"
echo "   - Start Command: npm start --prefix backend"
echo "   - Environment Variables:"
echo "     NODE_ENV=production"
echo "     JWT_SECRET=generate_random_key_here"
echo "     CLIENT_URL=https://your-frontend-railway-url"
echo ""
echo "8. Configure Frontend Service:"
echo "   - Build Command: npm run build --prefix frontend"
echo "   - Start Command: npm run preview --prefix frontend"
echo "   - Environment Variable:"
echo "     VITE_API_URL=https://your-backend-railway-url/api"
echo ""
echo "9. Deploy! (Auto-deploys on every GitHub push)"
echo ""

# Step 3: Instructions Summary
echo "📋 Summary"
echo "================================"
echo "✅ Code committed locally"
echo "⏳ Next: Create GitHub repo & push"
echo "⏳ Then: Deploy on Railway"
echo "⏳ Finally: Record demo video"
echo ""
